# --- Window settings ---
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800
FPS = 60
TITLE = "RFICS Arena"

# --- Arena settings ---
ARENA_WIDTH = 400
ARENA_HEIGHT = 400
ARENA_BORDER_THICKNESS = 5
ARENA_BORDER_COLOR = (255, 255, 255)
BACKGROUND_COLOR = (0, 0, 0)

ARENA_LEFT = (WINDOW_WIDTH - ARENA_WIDTH) // 2
ARENA_TOP = (WINDOW_HEIGHT - ARENA_HEIGHT) // 2

# --- Player settings ---
BONUS_SIZE_PER_HEALTH = 2

PLAYER_BASE_RADIUS= 20
PLAYER_BASE_HEALTH = 5

PLAYER_STARTING_RADIUS = PLAYER_BASE_RADIUS + (BONUS_SIZE_PER_HEALTH * PLAYER_BASE_HEALTH)
# --- Colors ---
WHITE = (255, 255, 255)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
